const C = {
    ADD_SPLIT: "ADD_SPLIT",
    ADD_EXERCISE: "ADD_EXERCISE",
    UPDATE_EXERCISE: "UPDATE_EXERCISE",
    START_WORKOUT: "START_WORKOUT",
    EDIT_SPLIT: "EDIT_SPLIT",
    ADD_WORKOUT: "ADD_WORKOUT",
    EDIT_WORKOUT: "EDIT_WORKOUT",
    UPDATE_WORKOUT: "UPDATE_WORKOUT",
    SELECT_EXERCISE: "SELECT_EXERCISE",
    UNSELECT_EXERCISE: "UNSELECT_EXERCISE"
};

export default C;

export const defaults = {
    LOCALSTORAGE_NAME: 'localWeights'
}

export const muscles = {
    CHEST: "CHEST",
    BACK: "BACK",
    LEGS: "LEGS",
    BIZEPS: "BIZEPS",
    TRIZEPS: "TRIZEPS",
    SHOULDER: "SHOULDER",
    ABS: "ABS"
}