const C = {
    ADD_SPLIT: "ADD_SPLIT",
    ADD_EXERCISE: "ADD_EXERCISE",
    UPDATE_EXERCISE: "UPDATE_EXERCISE",
    START_WORKOUT: "START_WORKOUT",
    EDIT_SPLIT: "EDIT_SPLIT",
    ADD_WORKOUT: "ADD_WORKOUT",
    EDIT_WORKOUT: "EDIT_WORKOUT",
    UPDATE_WORKOUT: "UPDATE_WORKOUT"
};

export default C;